apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-linkerd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-linkerd
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: nginx-linkerd
    spec:
      containers:
      - image: nginx
        name: nginx
      nodeSelector:
        kubernetes.io/hostname: c1-worker-2
