apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-istio
  name: nginx-istio
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-istio
  type: ClusterIP
status:
  loadBalancer: {}
